In [1]:
!pip install sodapy

Requirement already satisfied: sodapy in c:\users\chhab\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: requests>=2.20.0 in c:\users\chhab\anaconda3\lib\site-packages (from sodapy) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chhab\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\chhab\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\chhab\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\chhab\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (3.0.4)

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import pandas as pd
from sodapy import Socrata
from sqlalchemy import create_engine

In [3]:
client = Socrata("data.kcmo.org", None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [4]:
# API Calls
crimeresults = client.get("vsgj-uufz", limit=65000)

In [5]:
results_df = pd.DataFrame.from_records(crimeresults)
results_df

,report_no,reported_date,reported_time,from_date,from_time,to_date,to_time,offense,ibrs,description,...,sex,age,firearm_used_flag,zip_code,rep_dist,location,:@computed_region_kk66_ngf4,:@computed_region_9t2m_phkm,:@computed_region_my34_vmp8,:@computed_region_w4hf_t6bp
0,KC20000380,2020-01-02T14:00:30.000,14:00,2019-12-30T17:50:00.000,17:50,2019-12-30T18:00:00.000,18:00,Stealing – Shoplift,23C,Shoplifting,...,M,34,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KC20000485,2020-01-02T19:39:29.000,19:39,2020-01-02T19:39:00.000,19:39,2020-01-02T20:33:00.000,20:33,Outside State Warrant Arrest,90C,Disorderly Conduct,...,M,45,False,64127,PJ2173,NaN,NaN,NaN,NaN,NaN
2,KC20000494,2020-01-02T20:04:12.000,20:04,2020-01-02T21:00:00.000,21:00,NaN,NaN,City/Municipal Warrant Arrest,NaN,NaN,...,M,21,False,64086,NaN,NaN,NaN,NaN,NaN,NaN
3,KC20000565,2020-01-03T09:45:51.000,09:45,2020-01-03T09:09:00.000,09:09,NaN,NaN,State Warrant Arrest,NaN,NaN,...,F,36,False,64106,PJ1046,NaN,NaN,NaN,NaN,NaN
4,KC20000603,2020-01-03T12:10:50.000,12:10,2020-01-03T12:05:00.000,12:05,NaN,NaN,Stealing – Shoplift,23C,Shoplifting,...,NaN,NaN,False,64114,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60051,KC20048736,2020-07-22T08:04:30.000,08:04,2020-07-21T18:00:00.000,18:00,2020-07-22T06:30:00.000,06:30,Property Damage,290,Vandalism/Destruction of Property,...,M,47,False,64151,PP0561,"{'latitude': '39.22366', 'longitude': '-94.640...",163,5,3,66
60052,KC20055127,2020-08-15T16:20:12.000,16:20,2020-08-15T16:20:00.000,16:20,NaN,NaN,Burglary (Residential),220,Burglary/Breaking and Entering,...,F,62,False,64106,PJ2295,NaN,NaN,NaN,NaN,NaN
60053,KC20055047,2020-08-15T09:58:14.000,09:58,2020-05-01T00:01:00.000,00:01,2020-07-20T23:59:00.000,23:59,Identity Theft,26F,Identity Theft,...,U,NaN,False,64110,PJ4734,"{'latitude': '39.018837', 'longitude': '-94.56...",64,2,7,165
60054,KC20050432,2020-07-28T13:34:17.000,13:34,2020-07-28T13:30:00.000,13:30,NaN,NaN,Stealing – Shoplift,23C,Shoplifting,...,NaN,NaN,False,64131,NaN,"{'latitude': '38.948277', 'longitude': '-94.58...",162,1,7,163
60055,KC20053608,2020-08-10T06:42:02.000,06:42,2020-08-10T06:40:00.000,06:40,NaN,NaN,Assault (Aggravated),13A,Aggravated Assault,...,F,29,False,NaN,NaN,"{'latitude': '39.103739', 'longitude': '-94.58...",185,4,7,72

In [6]:
df=results_df.dropna(how='all')

In [1]:
df.columns

NameError: name 'NewCrimeDF' is not defined

In [8]:
importantcolumns = ['firearm_used_flag','zip_code','report_no', "offense", "description", "sex", "age","race"]

In [9]:
for column in importantcolumns:
    print(column)
    print(results_df[column].value_counts())
    print(f"\n")

firearm_used_flag
False    54311
True      5745
Name: firearm_used_flag, dtype: int64


zip_code
64130    3907
64127    3503
64111    3502
64134    2586
64132    2373
         ...
64142       1
64234       1
64506       1
66111       1
66101       1
Name: zip_code, Length: 134, dtype: int64


report_no
KC20035353    51
KC20026792    50
KC20004714    42
KC20051937    40
KC20035416    33
              ..
KC20027653     1
KC20054348     1
KC20023073     1
KC20015382     1
KC20047293     1
Name: report_no, Length: 34598, dtype: int64


offense
Domestic Violence Assault (Non-Aggravated)    5349
Assault (Aggravated)                          4205
Property Damage                               3876
Stolen Auto                                   3842
Stealing from Auto (Theft from Auto)          3299
                                              ...
False Imprisonment                               2
Tobacco Law Violation                            2
Discharge of Firearm (LEO Only)                  2
Carrying a Concealed Weapon                      2
Outside Correspondence                           1
Name: offense, Length: 133, dtype: int64


description
Simple Assault                              7955
Aggravated Assault                          6530
Vandalism/Destruction of Property           4929
Motor Vehicle Theft                         3842
Theft From Motor Vehicle                    3187
Burglary/Breaking and Entering              2955
Shoplifting                                 2814
All Other Offenses                          2445
Robbery                                     2130
All Other Larceny                           2026
Trespass of Real Property                   1960
Theft From Building                         1563
Theft of Vehicle Parts and Accessories      1487
Intimidation                                1170
Drug / Narcotic Violations                   981
Disorderly Conduct                           824
Stolen Property Offenses                     736
Driving Under the Influence                  631
False Pretenses / Swindle                    615
Identity Theft                               476
Counterfeiting / Forgery                     448
Weapon Law Violations                        443
Credit Card / Automatic Teller               396
Forcible Rape                                359
Family Offenses, Nonviolent                  345
Murder                                       315
Forcible Sodomy                              252
Arson                                        206
Wire Fraud                                   201
Embezzlement                                 186
Drug Equipment Violations                    167
Forcible Fondling                            100
Statutory Rape                                74
Pocket-Picking                                53
Curfew / Loitering / Vargancy Violations      53
Pornography / Obscene Material                45
Kidnapping / Abduction                        31
Purse-Snatching                               24
Extortion / Blackmail                         22
Hacking / Computer Invasion                   21
Theft From Coin-Operated Machine              17
Liquor Law Violations                         16
Bad Checks                                    15
Sexual Assault With An Object                 14
Justifiable Homicide                          14
Prostitution                                  14
DV Related Suicide                            11
Drunkenness                                   11
Welfare Fraud                                  9
Purchasing Prostitution                        8
Assisting or Promoting Prostitution            7
Impersonation                                  7
Commercial Sex Acts                            6
Incest                                         4
Animal Cruelty                                 3
Peeping Tom                                    2
Involuntary Servitude                          2
Betting / Wagering                             1
Name: description, dtype: int64


sex
M    32431
F    20507
U      577
Name: sex, dtype: int64


age
30    1758
25    1556
29    1555
27    1528
28    1477
      ...
94       3
96       2
91       2
99       1
98       1
Name: age, Length: 81, dtype: int64


race
B    25799
W    24569
U     2265
I      158
Name: race, dtype: int64

In [10]:
#df = results_df[importantcolumns]
#firearmtrue = df.loc[df['firearm_used_flag'] == True]
#firearmtrue

In [11]:
#for column in importantcolumns:
    #print(column)
    #print(firearmtrue[column].value_counts())
    #print(f"\n")

In [12]:
crime_df = df[importantcolumns]
crime_df

,firearm_used_flag,zip_code,report_no,offense,description,sex,age,race
0,False,NaN,KC20000380,Stealing – Shoplift,Shoplifting,M,34,B
1,False,64127,KC20000485,Outside State Warrant Arrest,Disorderly Conduct,M,45,B
2,False,64086,KC20000494,City/Municipal Warrant Arrest,NaN,M,21,B
3,False,64106,KC20000565,State Warrant Arrest,NaN,F,36,B
4,False,64114,KC20000603,Stealing – Shoplift,Shoplifting,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
60051,False,64151,KC20048736,Property Damage,Vandalism/Destruction of Property,M,47,B
60052,False,64106,KC20055127,Burglary (Residential),Burglary/Breaking and Entering,F,62,U
60053,False,64110,KC20055047,Identity Theft,Identity Theft,U,NaN,U
60054,False,64131,KC20050432,Stealing – Shoplift,Shoplifting,NaN,NaN,NaN
60055,False,NaN,KC20053608,Assault (Aggravated),Aggravated Assault,F,29,B

In [13]:
crime_df.to_csv('NewCrime.csv')